# -*- coding: utf-8 -*-
"""Fan ML Model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NCtlqvfHivO-WRS3cnSVzKrAGaDmulLG
"""

pip install scikit-learn

import pandas as pd
import numpy as np
#Read the dataset
energy_df = pd.read_csv(r"/content/appliance_energy.csv")
energy_df.head()

#energy_cons = f(temp)
import seaborn as sns
import matplotlib.pyplot as plt
plt.figure(figsize = (4, 4))
sns.scatterplot(x = "Temperature (°C)",
                y = "Energy Consumption (kWh)",
                data = energy_df)
plt.show()

sns.regplot(x = "Temperature (°C)",
            y = "Energy Consumption (kWh)",
            data = energy_df)

#energy_cons = f(temp)
#Selecting input(features) and output(target)
X = energy_df[['Temperature (°C)']]
y = energy_df[['Energy Consumption (kWh)']]
#y = f(x)

#Splitting the dataset into training and testing
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2,
                                                    random_state = 42)

X_train.shape

X.shape

X_test.shape

#Select the algorithm
from sklearn.linear_model import LinearRegression
energy_model = LinearRegression()
#Training the model
energy_model.fit(X_train, y_train)

energy_model.coef_

energy_model.intercept_ #value of c

#Evaluating the model
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

#Get the predicted output
y_pred = energy_model.predict(X_test)
y_pred

X_test[:5]

#Comparing with actual output
y_test[:5]

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(f"Mean Absolute Error is: {mae}")
print(f"Mean Squared Error is: {mse}")
print(f"R2 Score is:, {r2}")

#Visualize the result
plt.scatter(X_test, y_test, label = "Testing Data", color = 'r')
plt.plot(X_test, y_pred, label = "Regression Line", color = 'k')
plt.legend()

#Save the model
!pip install joblib

import joblib as jb
jb.dump(energy_model, r"C:\Users\MAYURI\OneDrive\Documents\Energy_Predictor.pkl")

